// Stretch and mobility catalog. Its own taxonomy, deliberately NOT part of
// makeMuscleLookup: anything registered there is counted as hypertrophy
// volume by the progression engine, and stretching is not. `targets` uses
// the MUSCLE_GROUPS vocabulary (plus a few regions lifts don't name) so a
// routine generator can match a session's muscle groups to stretches.
// Cue text is original; sequences of standard stretches are not
// copyrightable, but another app's wording and drawings are.

export type StretchType = 'static' | 'dynamic' | 'breath'
/** When a stretch belongs: 'pre' = warm-up drill (short, dynamic),
 * 'post' = cooldown hold, 'any' = either or standalone. */
export type StretchPhase = 'pre' | 'post' | 'any'

export interface Stretch {
  name: string
  region: string
  type: StretchType
  perSide: boolean
  defaultSec: number
  /** One to three short lines: setup, what to feel, breath. */
  cues: string[]
  targets: string[]
  phase: StretchPhase[]
  /** Needs nothing unless listed. */
  needs?: 'wall' | 'floor' | 'bar' | 'doorway' | 'chair'
}

export const STRETCHES: Stretch[] = [
  // ---- spine, back, breath ----
  {
    name: "Child's pose",
    region: 'back',
    type: 'static',
    perSide: false,
    defaultSec: 45,
    cues: ['Knees wide, sit back toward the heels, arms long.', 'Breathe into the back of the ribs.'],
    targets: ['back', 'shoulders'],
    phase: ['post', 'any'],
    needs: 'floor',
  },
  {
    name: 'Cat-cow',
    region: 'thoracic',
    type: 'dynamic',
    perSide: false,
    defaultSec: 40,
    cues: ['On all fours, round then arch, one breath per direction.', 'Move from the middle of the back, not the neck.'],
    targets: ['back', 'core'],
    phase: ['pre', 'post', 'any'],
    needs: 'floor',
  },
  {
    name: 'Sphinx',
    region: 'lower back',
    type: 'static',
    perSide: false,
    defaultSec: 40,
    cues: ['Forearms down, elbows under the shoulders, long neck.', 'Let the glutes and legs go heavy.'],
    targets: ['core', 'back'],
    phase: ['post', 'any'],
    needs: 'floor',
  },
  {
    name: 'Supine twist',
    region: 'lower back',
    type: 'static',
    perSide: true,
    defaultSec: 60,
    cues: ['On your back, knees drop to one side, shoulders stay flat.', 'Look the other way and let the ribs sink.'],
    targets: ['back', 'core', 'glutes'],
    phase: ['post', 'any'],
    needs: 'floor',
  },
  {
    name: 'Knees to chest',
    region: 'lower back',
    type: 'static',
    perSide: false,
    defaultSec: 45,
    cues: ['Hug both knees in, rock gently side to side.', 'Chin tucked, shoulders down.'],
    targets: ['back', 'glutes'],
    phase: ['post', 'any'],
    needs: 'floor',
  },
  {
    name: 'Seated twist',
    region: 'thoracic',
    type: 'static',
    perSide: true,
    defaultSec: 30,
    cues: ['Sit tall, rotate from the ribs, hand on the opposite knee.', 'Grow taller on the inhale, turn a little on the exhale.'],
    targets: ['back', 'core'],
    phase: ['any'],
    needs: 'chair',
  },
  {
    name: 'Box breathing',
    region: 'breath',
    type: 'breath',
    perSide: false,
    defaultSec: 60,
    cues: ['In for four, hold four, out for four, hold four.', 'Breathe low into the belly.'],
    targets: [],
    phase: ['post', 'any'],
  },
  // ---- thoracic & shoulders ----
  {
    name: 'Thread the needle',
    region: 'thoracic',
    type: 'static',
    perSide: true,
    defaultSec: 40,
    cues: ['From all fours, slide one arm under the other.', 'Rest the shoulder and temple down, hips stay high.'],
    targets: ['back', 'shoulders', 'rear delts'],
    phase: ['pre', 'post', 'any'],
    needs: 'floor',
  },
  {
    name: 'Open book',
    region: 'thoracic',
    type: 'dynamic',
    perSide: true,
    defaultSec: 40,
    cues: ['Side-lying, knees stacked and bent, arms together.', 'Open the top arm and follow the hand with your eyes.'],
    targets: ['back', 'chest', 'core'],
    phase: ['pre', 'post', 'any'],
    needs: 'floor',
  },
  {
    name: 'Puppy pose',
    region: 'shoulders',
    type: 'static',
    perSide: false,
    defaultSec: 45,
    cues: ['Hips stay over the knees, walk the hands forward.', 'Chest sinks toward the floor, arms long.'],
    targets: ['shoulders', 'back', 'triceps'],
    phase: ['post', 'any'],
    needs: 'floor',
  },
  {
    name: 'Wall slides',
    region: 'shoulders',
    type: 'dynamic',
    perSide: false,
    defaultSec: 40,
    cues: ['Back, elbows and wrists on the wall, slide up and down.', 'Ribs stay down; stop where the wrists want to leave the wall.'],
    targets: ['shoulders', 'back', 'traps'],
    phase: ['pre', 'any'],
    needs: 'wall',
  },
  {
    name: 'Arm circles',
    region: 'shoulders',
    type: 'dynamic',
    perSide: false,
    defaultSec: 30,
    cues: ['Small to large, then reverse.', 'Palms down, shoulders away from the ears.'],
    targets: ['shoulders'],
    phase: ['pre'],
  },
  {
    name: 'Scapular push-ups',
    region: 'shoulders',
    type: 'dynamic',
    perSide: false,
    defaultSec: 30,
    cues: ['Plank, arms straight, pinch the shoulder blades then spread them.', 'Nothing bends but the shoulder blades.'],
    targets: ['shoulders', 'chest'],
    phase: ['pre'],
    needs: 'floor',
  },
  {
    name: 'Dead hang',
    region: 'shoulders',
    type: 'static',
    perSide: false,
    defaultSec: 30,
    cues: ['Full grip, let the shoulders rise to the ears.', 'Breathe; feet off the floor if the grip allows.'],
    targets: ['back', 'shoulders'],
    phase: ['pre', 'any'],
    needs: 'bar',
  },
  {
    name: 'Cross-body shoulder',
    region: 'shoulders',
    type: 'static',
    perSide: true,
    defaultSec: 30,
    cues: ['Pull the arm across at chest height.', 'Keep that shoulder down, not shrugged.'],
    targets: ['shoulders', 'rear delts'],
    phase: ['post', 'any'],
  },
  {
    name: 'Lat stretch',
    region: 'lats',
    type: 'static',
    perSide: true,
    defaultSec: 40,
    cues: ['Hands on a rack or wall at hip height, sit the hips back.', 'Push the same-side hip away to lengthen the lat.'],
    targets: ['back'],
    phase: ['post', 'any'],
    needs: 'wall',
  },
  {
    name: 'Doorway pec stretch',
    region: 'chest',
    type: 'static',
    perSide: false,
    defaultSec: 40,
    cues: ['Forearms on the frame at shoulder height, step one foot through.', 'Chest forward, ribs down.'],
    targets: ['chest', 'shoulders'],
    phase: ['post', 'any'],
    needs: 'doorway',
  },
  {
    name: 'Seated chest opener',
    region: 'chest',
    type: 'static',
    perSide: false,
    defaultSec: 30,
    cues: ['Clasp the hands behind you, lift the chest.', 'Roll the shoulders back and down.'],
    targets: ['chest', 'shoulders'],
    phase: ['any'],
    needs: 'chair',
  },
  {
    name: 'Overhead triceps',
    region: 'arms',
    type: 'static',
    perSide: true,
    defaultSec: 30,
    cues: ['Elbow up, hand down the back.', 'Gently press the elbow with the other hand; ribs stay down.'],
    targets: ['triceps'],
    phase: ['post', 'any'],
  },
  {
    name: 'Forearm flexor stretch',
    region: 'forearms',
    type: 'static',
    perSide: true,
    defaultSec: 30,
    cues: ['Arm straight, palm up, pull the fingers back.', 'Then palm down for the extensors if there is time.'],
    targets: ['forearms'],
    phase: ['post', 'any'],
  },
  {
    name: 'Neck side stretch',
    region: 'neck',
    type: 'static',
    perSide: true,
    defaultSec: 30,
    cues: ['Ear toward the shoulder, opposite hand reaches for the floor.', 'Long exhale; no pulling on the head.'],
    targets: ['neck', 'traps'],
    phase: ['any'],
  },
  {
    name: 'Chin tucks',
    region: 'neck',
    type: 'dynamic',
    perSide: false,
    defaultSec: 30,
    cues: ['Glide the chin straight back, hold two seconds, release.', 'Eyes level the whole time.'],
    targets: ['neck'],
    phase: ['any'],
  },
  // ---- hips & glutes ----
  {
    name: 'Low lunge',
    region: 'hip flexors',
    type: 'static',
    perSide: true,
    defaultSec: 45,
    cues: ['Back knee down, tuck the tailbone, push the hips gently forward.', 'Squeeze the back glute to find it.'],
    targets: ['hip flexors', 'quads', 'glutes'],
    phase: ['pre', 'post', 'any'],
    needs: 'floor',
  },
  {
    name: 'Couch stretch',
    region: 'hip flexors',
    type: 'static',
    perSide: true,
    defaultSec: 60,
    cues: ['Back shin up the wall, front foot planted.', 'Stay tall, squeeze the glute; ease off if the knee complains.'],
    targets: ['quads', 'hip flexors'],
    phase: ['post', 'any'],
    needs: 'wall',
  },
  {
    name: 'Pigeon',
    region: 'glutes',
    type: 'static',
    perSide: true,
    defaultSec: 60,
    cues: ['Front shin angled, back leg long, hips square.', 'Fold forward only if it stays comfortable.'],
    targets: ['glutes'],
    phase: ['post', 'any'],
    needs: 'floor',
  },
  {
    name: 'Figure-4',
    region: 'glutes',
    type: 'static',
    perSide: true,
    defaultSec: 45,
    cues: ['On your back, ankle over the opposite knee.', 'Pull the bottom thigh in; head stays down.'],
    targets: ['glutes'],
    phase: ['post', 'any'],
    needs: 'floor',
  },
  {
    name: 'Seated figure-4',
    region: 'glutes',
    type: 'static',
    perSide: true,
    defaultSec: 40,
    cues: ['Ankle over the knee, sit tall, hinge forward.', 'Press the raised knee gently down.'],
    targets: ['glutes'],
    phase: ['any'],
    needs: 'chair',
  },
  {
    name: '90/90',
    region: 'hips',
    type: 'static',
    perSide: true,
    defaultSec: 45,
    cues: ['Both knees at right angles, sit tall.', 'Lean over the front shin with a flat back.'],
    targets: ['glutes', 'hip flexors'],
    phase: ['post', 'any'],
    needs: 'floor',
  },
  {
    name: 'Frog',
    region: 'adductors',
    type: 'static',
    perSide: false,
    defaultSec: 60,
    cues: ['Knees wide, ankles in line with the knees, forearms down.', 'Rock back an inch at a time; breathe.'],
    targets: ['adductors', 'glutes'],
    phase: ['post', 'any'],
    needs: 'floor',
  },
  {
    name: 'Butterfly',
    region: 'adductors',
    type: 'static',
    perSide: false,
    defaultSec: 45,
    cues: ['Soles together, sit tall, let the knees drop.', 'Hinge forward from the hips, not the back.'],
    targets: ['adductors', 'glutes'],
    phase: ['post', 'any'],
    needs: 'floor',
  },
  {
    name: 'Adductor rock',
    region: 'adductors',
    type: 'dynamic',
    perSide: true,
    defaultSec: 40,
    cues: ['Half kneel, other leg straight out to the side, foot flat.', 'Rock the hips back into the inner thigh and return.'],
    targets: ['adductors', 'hamstrings'],
    phase: ['pre', 'post', 'any'],
    needs: 'floor',
  },
  {
    name: 'Happy baby',
    region: 'hips',
    type: 'static',
    perSide: false,
    defaultSec: 60,
    cues: ['Hold the outsides of the feet, knees toward the armpits.', 'Tailbone stays heavy on the floor.'],
    targets: ['glutes', 'adductors', 'back'],
    phase: ['post', 'any'],
    needs: 'floor',
  },
  {
    name: 'Hip circles',
    region: 'hips',
    type: 'dynamic',
    perSide: false,
    defaultSec: 30,
    cues: ['Hands on hips, big slow circles, then the other way.', 'Knees soft, feet planted.'],
    targets: ['glutes', 'hip flexors'],
    phase: ['pre'],
  },
  {
    name: 'Leg swings',
    region: 'hips',
    type: 'dynamic',
    perSide: true,
    defaultSec: 30,
    cues: ['Hold something, swing the leg front to back.', 'Relaxed and tall; let the range grow each swing.'],
    targets: ['hamstrings', 'hip flexors', 'glutes'],
    phase: ['pre'],
  },
  {
    name: "World's greatest stretch",
    region: 'full body',
    type: 'dynamic',
    perSide: true,
    defaultSec: 45,
    cues: ['Long lunge, same-side elbow toward the instep.', 'Rotate and reach that hand to the ceiling, then repeat.'],
    targets: ['hip flexors', 'glutes', 'back', 'hamstrings'],
    phase: ['pre'],
    needs: 'floor',
  },
  {
    name: 'Walking lunge with twist',
    region: 'full body',
    type: 'dynamic',
    perSide: false,
    defaultSec: 45,
    cues: ['Step long, front knee over the ankle.', 'Rotate the torso toward the front leg, then step through.'],
    targets: ['quads', 'glutes', 'core'],
    phase: ['pre'],
  },
  {
    name: 'Deep squat hold',
    region: 'hips',
    type: 'static',
    perSide: false,
    defaultSec: 30,
    cues: ['Heels down, elbows push the knees out.', 'Chest up; shift side to side if it helps.'],
    targets: ['glutes', 'quads', 'adductors', 'calves'],
    phase: ['pre', 'any'],
  },
  // ---- hamstrings & calves ----
  {
    name: 'Standing forward fold',
    region: 'hamstrings',
    type: 'static',
    perSide: false,
    defaultSec: 40,
    cues: ['Hinge at the hips, let the head hang.', 'Soft knees; hold the elbows if it helps.'],
    targets: ['hamstrings', 'back'],
    phase: ['post', 'any'],
  },
  {
    name: 'Single-leg forward fold',
    region: 'hamstrings',
    type: 'static',
    perSide: true,
    defaultSec: 45,
    cues: ['Heel down, toes up, hinge until the hamstring speaks.', 'Flat back; hands on the thigh or shin.'],
    targets: ['hamstrings'],
    phase: ['post', 'any'],
  },
  {
    name: 'Supine hamstring',
    region: 'hamstrings',
    type: 'static',
    perSide: true,
    defaultSec: 45,
    cues: ['On your back, one leg up, hands or a strap behind the thigh.', 'Knee slightly soft; the other leg stays long.'],
    targets: ['hamstrings'],
    phase: ['post', 'any'],
    needs: 'floor',
  },
  {
    name: 'Seated straddle',
    region: 'hamstrings',
    type: 'static',
    perSide: false,
    defaultSec: 45,
    cues: ['Legs wide, toes up, walk the hands forward.', 'Flat back first, then let it round.'],
    targets: ['hamstrings', 'adductors'],
    phase: ['post', 'any'],
    needs: 'floor',
  },
  {
    name: 'Hamstring flossing',
    region: 'hamstrings',
    type: 'dynamic',
    perSide: true,
    defaultSec: 30,
    cues: ['Seated, straighten the knee and flex the foot, then release.', 'Smooth reps, no bouncing.'],
    targets: ['hamstrings'],
    phase: ['pre'],
    needs: 'chair',
  },
  {
    name: 'Inchworm',
    region: 'full body',
    type: 'dynamic',
    perSide: false,
    defaultSec: 45,
    cues: ['Fold, walk the hands out to a plank, walk the feet back in.', 'Legs as straight as they allow.'],
    targets: ['hamstrings', 'core', 'shoulders'],
    phase: ['pre'],
    needs: 'floor',
  },
  {
    name: 'Downward dog',
    region: 'posterior chain',
    type: 'static',
    perSide: false,
    defaultSec: 40,
    cues: ['Push the floor away, hips high, heels reach down.', 'Bent knees are fine; long spine matters more.'],
    targets: ['hamstrings', 'calves', 'shoulders', 'back'],
    phase: ['pre', 'post', 'any'],
    needs: 'floor',
  },
  {
    name: 'Wall calf stretch',
    region: 'calves',
    type: 'static',
    perSide: true,
    defaultSec: 40,
    cues: ['Back heel down, back knee straight, lean into the wall.', 'Toes point straight ahead.'],
    targets: ['calves'],
    phase: ['post', 'any'],
    needs: 'wall',
  },
  {
    name: 'Bent-knee calf stretch',
    region: 'calves',
    type: 'static',
    perSide: true,
    defaultSec: 30,
    cues: ['Same stance, now bend the back knee.', 'The stretch drops lower into the ankle.'],
    targets: ['calves'],
    phase: ['post', 'any'],
    needs: 'wall',
  },
  {
    name: 'Ankle rocks',
    region: 'ankles',
    type: 'dynamic',
    perSide: true,
    defaultSec: 30,
    cues: ['Half kneel, drive the knee over the toes, heel stays down.', 'Rock in and out; aim past the little toe.'],
    targets: ['calves'],
    phase: ['pre', 'any'],
    needs: 'floor',
  },
  {
    name: 'Legs up the wall',
    region: 'restorative',
    type: 'static',
    perSide: false,
    defaultSec: 90,
    cues: ['Hips close to the wall, legs resting up it.', 'Arms open, let everything be heavy.'],
    targets: ['hamstrings'],
    phase: ['post', 'any'],
    needs: 'wall',
  },
]

const byName = new Map(STRETCHES.map((s) => [s.name.toLowerCase(), s]))

export function stretchByName(name: string): Stretch | undefined {
  return byName.get(name.trim().toLowerCase())
}
