// Stretch and mobility catalog. Its own taxonomy, deliberately NOT part of
// makeMuscleLookup: anything registered there is counted as hypertrophy
// volume by the progression engine, and stretching is not. `targets` uses
// the MUSCLE_GROUPS vocabulary (plus a few regions lifts don't name) so a
// routine generator can match a session's muscle groups to stretches.
// Cue text is original; sequences of standard stretches are not
// copyrightable, but another app's wording and drawings are.

export type StretchType = 'static' | 'dynamic' | 'breath'
/** When a stretch belongs: 'pre' = warm-up drill (short, dynamic),
 * 'post' = cooldown hold, 'any' = either or standalone. */
export type StretchPhase = 'pre' | 'post' | 'any'

export interface Stretch {
  name: string
  region: string
  type: StretchType
  perSide: boolean
  defaultSec: number
  /** One to three short lines: setup, what to feel, breath. */
  cues: string[]
  targets: string[]
  phase: StretchPhase[]
  /** Needs nothing unless listed. */
  needs?: 'wall' | 'floor' | 'bar' | 'doorway' | 'chair'
}

export const STRETCHES: Stretch[] = [
  // ---- spine, back, breath ----
  {
    name: "Child's pose",
    region: 'back',
    type: 'static',
    perSide: false,
    defaultSec: 45,
    cues: ['Knees wide, sit back toward the heels, arms long.'],
    targets: ['back', 'shoulders'],
    phase: ['post', 'any'],
    needs: 'floor',
  },
  {
    name: 'Cat-cow',
    region: 'thoracic',
    type: 'dynamic',
    perSide: false,
    defaultSec: 40,
    cues: ['On all fours, round then arch, one breath per direction.'],
    targets: ['back', 'core'],
    phase: ['pre', 'post', 'any'],
    needs: 'floor',
  },
  {
    name: 'Sphinx',
    region: 'lower back',
    type: 'static',
    perSide: false,
    defaultSec: 40,
    cues: ['Forearms down, elbows under the shoulders, long neck.'],
    targets: ['core', 'back'],
    phase: ['post', 'any'],
    needs: 'floor',
  },
  {
    name: 'Supine twist',
    region: 'lower back',
    type: 'static',
    perSide: true,
    defaultSec: 60,
    cues: ['On your back, knees drop to one side, shoulders stay flat.'],
    targets: ['back', 'core', 'glutes'],
    phase: ['post', 'any'],
    needs: 'floor',
  },
  {
    name: 'Knees to chest',
    region: 'lower back',
    type: 'static',
    perSide: false,
    defaultSec: 45,
    cues: ['Hug both knees in, rock gently side to side.'],
    targets: ['back', 'glutes'],
    phase: ['post', 'any'],
    needs: 'floor',
  },
  {
    name: 'Seated twist',
    region: 'thoracic',
    type: 'static',
    perSide: true,
    defaultSec: 30,
    cues: ['Sit tall, rotate from the ribs, hand on the opposite knee.'],
    targets: ['back', 'core'],
    phase: ['any'],
    needs: 'chair',
  },
  {
    name: 'Box breathing',
    region: 'breath',
    type: 'breath',
    perSide: false,
    defaultSec: 60,
    cues: ['In for four, hold four, out for four, hold four.'],
    targets: [],
    phase: ['post', 'any'],
  },
  // ---- thoracic & shoulders ----
  {
    name: 'Thread the needle',
    region: 'thoracic',
    type: 'static',
    perSide: true,
    defaultSec: 40,
    cues: ['From all fours, slide one arm under the other.'],
    targets: ['back', 'shoulders', 'rear delts'],
    phase: ['pre', 'post', 'any'],
    needs: 'floor',
  },
  {
    name: 'Open book',
    region: 'thoracic',
    type: 'dynamic',
    perSide: true,
    defaultSec: 40,
    cues: ['Side-lying, knees stacked, open the top arm and follow it with your eyes.'],
    targets: ['back', 'chest', 'core'],
    phase: ['pre', 'post', 'any'],
    needs: 'floor',
  },
  {
    name: 'Puppy pose',
    region: 'shoulders',
    type: 'static',
    perSide: false,
    defaultSec: 45,
    cues: ['Hips stay over the knees, walk the hands forward.'],
    targets: ['shoulders', 'back', 'triceps'],
    phase: ['post', 'any'],
    needs: 'floor',
  },
  {
    name: 'Wall slides',
    region: 'shoulders',
    type: 'dynamic',
    perSide: false,
    defaultSec: 40,
    cues: ['Back, elbows and wrists on the wall, slide up and down.'],
    targets: ['shoulders', 'back', 'traps'],
    phase: ['pre', 'any'],
    needs: 'wall',
  },
  {
    name: 'Arm circles',
    region: 'shoulders',
    type: 'dynamic',
    perSide: false,
    defaultSec: 30,
    cues: ['Small to large, then reverse.'],
    targets: ['shoulders'],
    phase: ['pre'],
  },
  {
    name: 'Scapular push-ups',
    region: 'shoulders',
    type: 'dynamic',
    perSide: false,
    defaultSec: 30,
    cues: ['Plank, arms straight, pinch the shoulder blades then spread them.'],
    targets: ['shoulders', 'chest'],
    phase: ['pre'],
    needs: 'floor',
  },
  {
    name: 'Dead hang',
    region: 'shoulders',
    type: 'static',
    perSide: false,
    defaultSec: 30,
    cues: ['Full grip, let the shoulders rise to the ears.'],
    targets: ['back', 'shoulders'],
    phase: ['pre', 'any'],
    needs: 'bar',
  },
  {
    name: 'Cross-body shoulder',
    region: 'shoulders',
    type: 'static',
    perSide: true,
    defaultSec: 30,
    cues: ['Pull the arm across at chest height.'],
    targets: ['shoulders', 'rear delts'],
    phase: ['post', 'any'],
  },
  {
    name: 'Lat stretch',
    region: 'lats',
    type: 'static',
    perSide: true,
    defaultSec: 40,
    cues: ['Hands on a rack or wall, sit the hips back.'],
    targets: ['back'],
    phase: ['post', 'any'],
    needs: 'wall',
  },
  {
    name: 'Doorway pec stretch',
    region: 'chest',
    type: 'static',
    perSide: false,
    defaultSec: 40,
    cues: ['Forearms on the frame at shoulder height, step one foot through.'],
    targets: ['chest', 'shoulders'],
    phase: ['post', 'any'],
    needs: 'doorway',
  },
  {
    name: 'Seated chest opener',
    region: 'chest',
    type: 'static',
    perSide: false,
    defaultSec: 30,
    cues: ['Clasp the hands behind you, lift the chest.'],
    targets: ['chest', 'shoulders'],
    phase: ['any'],
    needs: 'chair',
  },
  {
    name: 'Overhead triceps',
    region: 'arms',
    type: 'static',
    perSide: true,
    defaultSec: 30,
    cues: ['Elbow up, hand down the back.'],
    targets: ['triceps'],
    phase: ['post', 'any'],
  },
  {
    name: 'Forearm flexor stretch',
    region: 'forearms',
    type: 'static',
    perSide: true,
    defaultSec: 30,
    cues: ['Arm straight, palm up, pull the fingers back.'],
    targets: ['forearms'],
    phase: ['post', 'any'],
  },
  {
    name: 'Neck side stretch',
    region: 'neck',
    type: 'static',
    perSide: true,
    defaultSec: 30,
    cues: ['Ear toward the shoulder, opposite hand reaches for the floor.'],
    targets: ['neck', 'traps'],
    phase: ['any'],
  },
  {
    name: 'Chin tucks',
    region: 'neck',
    type: 'dynamic',
    perSide: false,
    defaultSec: 30,
    cues: ['Glide the chin straight back, hold two seconds, release.'],
    targets: ['neck'],
    phase: ['any'],
  },
  // ---- hips & glutes ----
  {
    name: 'Low lunge',
    region: 'hip flexors',
    type: 'static',
    perSide: true,
    defaultSec: 45,
    cues: ['Back knee down, tuck the tailbone, push the hips gently forward.'],
    targets: ['hip flexors', 'quads', 'glutes'],
    phase: ['pre', 'post', 'any'],
    needs: 'floor',
  },
  {
    name: 'Couch stretch',
    region: 'hip flexors',
    type: 'static',
    perSide: true,
    defaultSec: 60,
    cues: ['Back shin up the wall, front foot planted.'],
    targets: ['quads', 'hip flexors'],
    phase: ['post', 'any'],
    needs: 'wall',
  },
  {
    name: 'Pigeon',
    region: 'glutes',
    type: 'static',
    perSide: true,
    defaultSec: 60,
    cues: ['Front shin angled, back leg long, hips square.'],
    targets: ['glutes'],
    phase: ['post', 'any'],
    needs: 'floor',
  },
  {
    name: 'Figure-4',
    region: 'glutes',
    type: 'static',
    perSide: true,
    defaultSec: 45,
    cues: ['On your back, ankle over the opposite knee.'],
    targets: ['glutes'],
    phase: ['post', 'any'],
    needs: 'floor',
  },
  {
    name: 'Seated figure-4',
    region: 'glutes',
    type: 'static',
    perSide: true,
    defaultSec: 40,
    cues: ['Ankle over the knee, sit tall, hinge forward.'],
    targets: ['glutes'],
    phase: ['any'],
    needs: 'chair',
  },
  {
    name: '90/90',
    region: 'hips',
    type: 'static',
    perSide: true,
    defaultSec: 45,
    cues: ['Both knees at right angles, sit tall.'],
    targets: ['glutes', 'hip flexors'],
    phase: ['post', 'any'],
    needs: 'floor',
  },
  {
    name: 'Frog',
    region: 'adductors',
    type: 'static',
    perSide: false,
    defaultSec: 60,
    cues: ['Knees wide, ankles in line with the knees, forearms down.'],
    targets: ['adductors', 'glutes'],
    phase: ['post', 'any'],
    needs: 'floor',
  },
  {
    name: 'Butterfly',
    region: 'adductors',
    type: 'static',
    perSide: false,
    defaultSec: 45,
    cues: ['Soles together, sit tall, let the knees drop.'],
    targets: ['adductors', 'glutes'],
    phase: ['post', 'any'],
    needs: 'floor',
  },
  {
    name: 'Adductor rock',
    region: 'adductors',
    type: 'dynamic',
    perSide: true,
    defaultSec: 40,
    cues: ['Half kneel, other leg straight out to the side, rock the hips back.'],
    targets: ['adductors', 'hamstrings'],
    phase: ['pre', 'post', 'any'],
    needs: 'floor',
  },
  {
    name: 'Happy baby',
    region: 'hips',
    type: 'static',
    perSide: false,
    defaultSec: 60,
    cues: ['Hold the outsides of the feet, knees toward the armpits.'],
    targets: ['glutes', 'adductors', 'back'],
    phase: ['post', 'any'],
    needs: 'floor',
  },
  {
    name: 'Hip circles',
    region: 'hips',
    type: 'dynamic',
    perSide: false,
    defaultSec: 30,
    cues: ['Hands on hips, big slow circles, then the other way.'],
    targets: ['glutes', 'hip flexors'],
    phase: ['pre'],
  },
  {
    name: 'Leg swings',
    region: 'hips',
    type: 'dynamic',
    perSide: true,
    defaultSec: 30,
    cues: ['Hold something, swing the leg front to back.'],
    targets: ['hamstrings', 'hip flexors', 'glutes'],
    phase: ['pre'],
  },
  {
    name: "World's greatest stretch",
    region: 'full body',
    type: 'dynamic',
    perSide: true,
    defaultSec: 45,
    cues: ['Long lunge, elbow to the instep, then rotate and reach up.'],
    targets: ['hip flexors', 'glutes', 'back', 'hamstrings'],
    phase: ['pre'],
    needs: 'floor',
  },
  {
    name: 'Walking lunge with twist',
    region: 'full body',
    type: 'dynamic',
    perSide: false,
    defaultSec: 45,
    cues: ['Step long, then rotate the torso toward the front leg.'],
    targets: ['quads', 'glutes', 'core'],
    phase: ['pre'],
  },
  {
    name: 'Deep squat hold',
    region: 'hips',
    type: 'static',
    perSide: false,
    defaultSec: 30,
    cues: ['Heels down, elbows push the knees out.'],
    targets: ['glutes', 'quads', 'adductors', 'calves'],
    phase: ['pre', 'any'],
  },
  // ---- hamstrings & calves ----
  {
    name: 'Standing forward fold',
    region: 'hamstrings',
    type: 'static',
    perSide: false,
    defaultSec: 40,
    cues: ['Hinge at the hips, let the head hang.'],
    targets: ['hamstrings', 'back'],
    phase: ['post', 'any'],
  },
  {
    name: 'Single-leg forward fold',
    region: 'hamstrings',
    type: 'static',
    perSide: true,
    defaultSec: 45,
    cues: ['Heel down, toes up, hinge until the hamstring speaks.'],
    targets: ['hamstrings'],
    phase: ['post', 'any'],
  },
  {
    name: 'Supine hamstring',
    region: 'hamstrings',
    type: 'static',
    perSide: true,
    defaultSec: 45,
    cues: ['One leg up, hands or a strap behind the thigh.'],
    targets: ['hamstrings'],
    phase: ['post', 'any'],
    needs: 'floor',
  },
  {
    name: 'Seated straddle',
    region: 'hamstrings',
    type: 'static',
    perSide: false,
    defaultSec: 45,
    cues: ['Legs wide, toes up, walk the hands forward.'],
    targets: ['hamstrings', 'adductors'],
    phase: ['post', 'any'],
    needs: 'floor',
  },
  {
    name: 'Hamstring flossing',
    region: 'hamstrings',
    type: 'dynamic',
    perSide: true,
    defaultSec: 30,
    cues: ['Seated, straighten the knee and flex the foot, then release.'],
    targets: ['hamstrings'],
    phase: ['pre'],
    needs: 'chair',
  },
  {
    name: 'Inchworm',
    region: 'full body',
    type: 'dynamic',
    perSide: false,
    defaultSec: 45,
    cues: ['Fold, walk the hands out to a plank, walk the feet back in.'],
    targets: ['hamstrings', 'core', 'shoulders'],
    phase: ['pre'],
    needs: 'floor',
  },
  {
    name: 'Downward dog',
    region: 'posterior chain',
    type: 'static',
    perSide: false,
    defaultSec: 40,
    cues: ['Push the floor away, hips high, heels reach down.'],
    targets: ['hamstrings', 'calves', 'shoulders', 'back'],
    phase: ['pre', 'post', 'any'],
    needs: 'floor',
  },
  {
    name: 'Wall calf stretch',
    region: 'calves',
    type: 'static',
    perSide: true,
    defaultSec: 40,
    cues: ['Back heel down, back knee straight, lean into the wall.'],
    targets: ['calves'],
    phase: ['post', 'any'],
    needs: 'wall',
  },
  {
    name: 'Bent-knee calf stretch',
    region: 'calves',
    type: 'static',
    perSide: true,
    defaultSec: 30,
    cues: ['Same stance, now bend the back knee.'],
    targets: ['calves'],
    phase: ['post', 'any'],
    needs: 'wall',
  },
  {
    name: 'Ankle rocks',
    region: 'ankles',
    type: 'dynamic',
    perSide: true,
    defaultSec: 30,
    cues: ['Half kneel, drive the knee over the toes, heel stays down.'],
    targets: ['calves'],
    phase: ['pre', 'any'],
    needs: 'floor',
  },
  {
    name: 'Legs up the wall',
    region: 'restorative',
    type: 'static',
    perSide: false,
    defaultSec: 90,
    cues: ['Hips close to the wall, legs resting up it.'],
    targets: ['hamstrings'],
    phase: ['post', 'any'],
    needs: 'wall',
  },
]

const byName = new Map(STRETCHES.map((s) => [s.name.toLowerCase(), s]))

export function stretchByName(name: string): Stretch | undefined {
  return byName.get(name.trim().toLowerCase())
}